### ISSUE TITLE
dataset details

### ISSUE THREAD

**Issue by bheekya** [minhnguyen-cs/mtsne#2]
can you please provide the dataset details

**Comment by minhnguyen-cs** [comment]
Hi,

Thank you for your interest in our work.

We performed experiments on 2 multivariate time series dataset:  ATOM-HP a coarse-grained
time series dataset collected from our study, and EEG dataset - a fine-grained one from UCI machine learning [repository](https://archive.ics.uci.edu/ml/datasets/eeg+database).

The dataset details along with the experimental setups are provided in [[pdf](https://minhnguyen-cs.github.io/download/amia2016.pdf)] (Section 4.1 and 4.2) or [[slides](https://minhnguyen-cs.github.io/download/amia2016_slide.pdf)] (short summary slide 15)

Best,
Minh
